[package]
name = "leelacoin"
version = "0.0.1"
authors = ["Ofek Shochat"]
edition = "2018"

[dependencies]
sha3 = "*"
hex = "*"
snow = "0.8.0"
serde = "*"
serde_json = "1.0"
clap = "*"
once_cell = "1.5"
lazy_static = "*"