[package]
name = "leelacoin"
version = "0.0.1"
authors = ["Ofek Shochat"]
edition = "2018"

[dependencies]
sha3 = "*"
hex = "*"
serde = "*"
serde_json = "1.0"
once_cell = "1.5"
miniz_oxide = "0.4.4"
chrono = "*"
ed25519-dalek = "*"
rand = "*"
simple_logger = "*"
log = "*"